version: "3.9"
services:
  db:
    image: mongo
    ports:
      - "27017:27017"
    logging:
      driver: none
  api:
    build: .
    environment:
      MONGO_URI: mongodb://db/reactwitter
    depends_on:
      - db
    ports:
      - "4000:4000"
    volumes:
      - .:/home/app